# Generated by Django 5.2.4 on 2025-08-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('processing', 'Proccessing'), ('cancelled', 'Cancelled')], default='processing', max_length=20)),
            ],
        ),
    ]
