# Generated by Django 5.2.4 on 2025-08-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='url',
            field=models.CharField(default=None, max_length=400),
        ),
    ]
