# Generated by Django 5.2.4 on 2025-08-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appliedjobs_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjobs',
            name='id',
        ),
        migrations.AlterField(
            model_name='appliedjobs',
            name='job_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
