matching_jobs=[{'id': '2847589',
  'employment_type': 'job',
  'title': 'Computer Operator Executive',
  'url': 'https://internshala.com/job/detail/fresher-remote-part-time-computer-operator-executive-job-at-devforce1754397227',
  'company_name': 'DevForce',
  'internship_logo': '/static/images/search/placeholder_logo.svg',
  'locations': ['Manish is testing'],
  'salary': '₹ 4,00,000 - 7,00,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2847441',
  'employment_type': 'job',
  'title': 'Senior Software Developer',
  'url': 'https://internshala.com/job/detail/remote-senior-software-developer-job-at-lumio-partners1754392645',
  'company_name': 'Lumio Partners',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2Fiwryonf1k8y-9387.png.webp',
  'locations': ['Work from home'],
  'salary': '₹ 5,00,000 - 10,00,000',
  'experience': '1 year(s)',
  'posted_at': None},
 {'id': '2847253',
  'employment_type': 'job',
  'title': 'Backend Developer',
  'url': 'https://internshala.com/job/detail/fresher-remote-backend-developer-job-at-api-labz1754382890',
  'company_name': 'API Labz',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2Fexboaqm1ygu-25320.png.webp',
  'locations': ['Work from home'],
  'salary': '₹ 4,00,000 - 6,00,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2846267',
  'employment_type': 'job',
  'title': 'Senior Backend Developer',
  'url': 'https://internshala.com/job/detail/remote-senior-backend-developer-job-at-weframe-tech1754378646',
  'company_name': 'Weframe Tech',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2Fews6m0i1jjq-7754.png.webp',
  'locations': ['Work from home'],
  'salary': '₹ 5,00,000 - 10,00,000',
  'experience': '1 year(s)',
  'posted_at': None},
 {'id': '2847023',
  'employment_type': 'job',
  'title': 'Web Developer',
  'url': 'https://internshala.com/job/detail/fresher-remote-web-developer-job-at-valcon-infotech1754377772',
  'company_name': 'Valcon Infotech',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2F6utuyu7vurx-78554.png.webp',
  'locations': ['Work from home'],
  'salary': '₹ 5,00,000 - 8,00,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2846965',
  'employment_type': 'job',
  'title': 'Junior Software Engineer',
  'url': 'https://internshala.com/job/detail/fresher-remote-junior-software-engineer-job-at-mediacom-india1754375216',
  'company_name': 'MediaCom India',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2Fh02v7a8fr91-9207.png.webp',
  'locations': ['Work from home'],
  'salary': '₹ 5,00,000 - 8,00,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2846859',
  'employment_type': 'job',
  'title': 'Full Stack Developer',
  'url': 'https://internshala.com/job/detail/full-stack-developer-job-in-delhi-at-boyswork1754365752',
  'company_name': 'Boys@Work',
  'internship_logo': '/static/images/search/placeholder_logo.svg',
  'locations': ['Delhi'],
  'salary': '₹ 3,00,000 - 6,00,000',
  'experience': '1 year(s)',
  'posted_at': None},
 {'id': '2846241',
  'employment_type': 'job',
  'title': 'Front End Developer',
  'url': 'https://internshala.com/job/detail/remote-front-end-developer-job-at-sk-info-techies1754298043',
  'company_name': 'SK Info Techies',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2F60d97ea92f7a31624866473.jpg.webp',
  'locations': ['Work from home'],
  'salary': '₹ 2,00,000 - 3,20,000',
  'experience': '1 year(s)',
  'posted_at': None},
 {'id': '2846271',
  'employment_type': 'job',
  'title': 'Full Stack Developer',
  'url': 'https://internshala.com/job/detail/fresher-remote-full-stack-developer-job-at-rapidquest1754304205',
  'company_name': 'RapidQuest',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2F5mb6tovu3i5-6149.png.webp',
  'locations': ['Work from home'],
  'salary': '₹ 6,00,000 - 7,00,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2843335',
  'employment_type': 'job',
  'title': 'Senior Full Stack Developer',
  'url': 'https://internshala.com/job/detail/remote-senior-full-stack-developer-job-at-aimsoft-technologies1754290979',
  'company_name': 'Aimsoft Technologies',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2F5e2fdf128b61d1580195602.jpg.webp',
  'locations': ['Work from home'],
  'salary': '₹ 3,00,000',
  'experience': '1 year(s)',
  'posted_at': None},
 {'id': '2843362',
  'employment_type': 'job',
  'title': 'Search Engine Optimization (SEO) Associate',
  'url': 'https://internshala.com/job/detail/remote-search-engine-optimization-seo-associate-job-at-xoom-digital1754290887',
  'company_name': 'Xoom Digital',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2F625d0b958800f1650264981.jpg.webp',
  'locations': ['Work from home'],
  'salary': '₹ 2,00,000 - 3,00,000',
  'experience': '1 year(s)',
  'posted_at': None},
 {'id': '2843024',
  'employment_type': 'job',
  'title': 'Junior Python Developer',
  'url': 'https://internshala.com/job/detail/remote-junior-python-developer-job-at-codezero2pi-solution-opc-private-limited1754289968',
  'company_name': 'Codezero2pi Solution (OPC) Private Limited',
  'internship_logo': '/static/images/search/placeholder_logo.svg',
  'locations': ['Work from home'],
  'salary': '₹ 4,00,000 - 6,00,000',
  'experience': '1 year(s)',
  'posted_at': None},
 {'id': '2845914',
  'employment_type': 'job',
  'title': 'Junior Front End Developer',
  'url': 'https://internshala.com/job/detail/fresher-remote-junior-front-end-developer-job-at-mediacom-india1754289531',
  'company_name': 'MediaCom India',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2Fh02v7a8fr91-9207.png.webp',
  'locations': ['Work from home'],
  'salary': '₹ 5,00,000 - 8,00,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2845915',
  'employment_type': 'job',
  'title': 'Junior Backend Developer',
  'url': 'https://internshala.com/job/detail/fresher-remote-junior-backend-developer-job-at-mediacom-india1754289504',
  'company_name': 'MediaCom India',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2Fh02v7a8fr91-9207.png.webp',
  'locations': ['Work from home'],
  'salary': '₹ 5,00,000 - 8,00,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2845198',
  'employment_type': 'job',
  'title': 'Mathematician',
  'url': 'https://internshala.com/job/detail/remote-part-time-mathematician-job-at-crossing-hurdles1754288176',
  'company_name': 'Crossing Hurdles',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2Ffdheb0miu5b-102893.png.webp',
  'locations': ['Work from home'],
  'salary': '₹ 10,00,000 - 30,00,000',
  'experience': '1 year(s)',
  'posted_at': None},
 {'id': '2845470',
  'employment_type': 'job',
  'title': 'DevOps Engineer',
  'url': 'https://internshala.com/job/detail/fresher-remote-devops-engineer-job-at-aaptatt1754285968',
  'company_name': 'Aaptatt',
  'internship_logo': '/static/images/search/placeholder_logo.svg',
  'locations': ['Work from home'],
  'salary': '₹ 3,00,000 - 3,25,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2845924',
  'employment_type': 'job',
  'title': 'Associate Web Developer',
  'url': 'https://internshala.com/job/detail/fresher-remote-associate-web-developer-job-at-mediacom-india1754283860',
  'company_name': 'MediaCom India',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2Fh02v7a8fr91-9207.png.webp',
  'locations': ['Work from home'],
  'salary': '₹ 5,00,000 - 8,00,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2845917',
  'employment_type': 'job',
  'title': 'Python Developer',
  'url': 'https://internshala.com/job/detail/fresher-remote-python-developer-job-at-mediacom-india1754283308',
  'company_name': 'MediaCom India',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2Fh02v7a8fr91-9207.png.webp',
  'locations': ['Work from home'],
  'salary': '₹ 5,00,000 - 8,00,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2845256',
  'employment_type': 'job',
  'title': 'Backend Associate Executive',
  'url': 'https://internshala.com/job/detail/fresher-remote-part-time-backend-associate-executive-job-at-devforce1754133891',
  'company_name': 'DevForce',
  'internship_logo': '/static/images/search/placeholder_logo.svg',
  'locations': ['Work from home'],
  'salary': '₹ 4,00,000 - 7,00,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2844977',
  'employment_type': 'job',
  'title': 'Software Engineer',
  'url': 'https://internshala.com/job/detail/fresher-remote-software-engineer-job-at-mediacom-india1754125965',
  'company_name': 'MediaCom India',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2Fh02v7a8fr91-9207.png.webp',
  'locations': ['Work from home'],
  'salary': '₹ 5,00,000 - 8,00,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2844962',
  'employment_type': 'job',
  'title': 'Associate Software Engineer',
  'url': 'https://internshala.com/job/detail/fresher-remote-associate-software-engineer-job-at-valcon-infotech1754125049',
  'company_name': 'Valcon Infotech',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2F6utuyu7vurx-78554.png.webp',
  'locations': ['Work from home'],
  'salary': '₹ 5,00,000 - 8,00,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2844956',
  'employment_type': 'job',
  'title': 'Associate Software Developer',
  'url': 'https://internshala.com/job/detail/fresher-remote-associate-software-developer-job-at-valcon-infotech1754124874',
  'company_name': 'Valcon Infotech',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2F6utuyu7vurx-78554.png.webp',
  'locations': ['Work from home'],
  'salary': '₹ 5,00,000 - 8,00,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2844980',
  'employment_type': 'job',
  'title': 'Software Developer',
  'url': 'https://internshala.com/job/detail/fresher-remote-software-developer-job-at-mediacom-india1754115016',
  'company_name': 'MediaCom India',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2Fh02v7a8fr91-9207.png.webp',
  'locations': ['Work from home'],
  'salary': '₹ 5,00,000 - 8,00,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2844972',
  'employment_type': 'job',
  'title': 'Full Stack Developer',
  'url': 'https://internshala.com/job/detail/fresher-remote-full-stack-developer-job-at-mediacom-india1754114685',
  'company_name': 'MediaCom India',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2Fh02v7a8fr91-9207.png.webp',
  'locations': ['Work from home'],
  'salary': '₹ 4,00,000 - 7,00,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2844965',
  'employment_type': 'job',
  'title': 'Junior Software Developer',
  'url': 'https://internshala.com/job/detail/fresher-remote-junior-software-developer-job-at-mediacom-india1754114378',
  'company_name': 'MediaCom India',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2Fh02v7a8fr91-9207.png.webp',
  'locations': ['Work from home'],
  'salary': '₹ 5,00,000 - 8,00,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2843661',
  'employment_type': 'job',
  'title': 'GoHighLevel Expert',
  'url': 'https://internshala.com/job/detail/remote-gohighlevel-expert-job-at-branding-house-llc-fz1754057085',
  'company_name': 'Branding House LLC-FZ',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2Fdcj8ryel8e3-22538.png.webp',
  'locations': ['Work from home'],
  'salary': '₹ 7,20,000',
  'experience': '1 year(s)',
  'posted_at': None},
 {'id': '2841615',
  'employment_type': 'job',
  'title': 'Technical Engineer',
  'url': 'https://internshala.com/job/detail/fresher-technical-engineer-job-in-gurgaon-at-klassify-technology-pvt-ltd1754055122',
  'company_name': 'Klassify Technology Pvt. Ltd.',
  'internship_logo': '/static/images/search/placeholder_logo.svg',
  'locations': ['Gurgaon'],
  'salary': '₹ 2,64,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2841677',
  'employment_type': 'job',
  'title': 'Associate Quantitative System Developer',
  'url': 'https://internshala.com/job/detail/associate-quantitative-system-developer-job-in-multiple-locations-at-quantglobal1754052872',
  'company_name': 'QuantGlobal',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2Fh1e2lcju2xd-3860.jpeg',
  'locations': ['Delhi', 'Ghaziabad', 'Greater Noida', 'Noida'],
  'salary': '₹ 6,00,000 - 12,00,000',
  'experience': '1 year(s)',
  'posted_at': None},
 {'id': '2842332',
  'employment_type': 'job',
  'title': 'Full Stack Developer',
  'url': 'https://internshala.com/job/detail/remote-full-stack-developer-job-at-therapymantra1754050399',
  'company_name': 'TherapyMantra',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2Fdouch3y35e8-22638.png.webp',
  'locations': ['Work from home'],
  'salary': '₹ 4,80,000 - 9,60,000',
  'experience': '1 year(s)',
  'posted_at': None},
 {'id': '2844356',
  'employment_type': 'job',
  'title': 'Back-End Executive',
  'url': 'https://internshala.com/job/detail/fresher-remote-part-time-back-end-executive-job-at-turbosoft-solutions1754045313',
  'company_name': 'Turbosoft Solutions',
  'internship_logo': '/static/images/search/placeholder_logo.svg',
  'locations': ['Work from home'],
  'salary': '₹ 4,00,000 - 7,00,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2844163',
  'employment_type': 'job',
  'title': 'PHP Developer',
  'url': 'https://internshala.com/job/detail/php-developer-job-in-delhi-at-gotech-digi-marketing-solutions1754037127',
  'company_name': 'Gotech Digi Marketing Solutions',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2F62623172b721f1650602354.jpg.webp',
  'locations': ['Delhi'],
  'salary': '₹ 2,40,000 - 3,60,000',
  'experience': '1 year(s)',
  'posted_at': None},
 {'id': '2842700',
  'employment_type': 'job',
  'title': 'Software Developer',
  'url': 'https://internshala.com/job/detail/fresher-remote-software-developer-job-at-dr-rajnesh-kumar1754036690',
  'company_name': 'PaymentKro',
  'internship_logo': '/static/images/search/placeholder_logo.svg',
  'locations': ['Work from home'],
  'salary': '₹ 3,00,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2841825',
  'employment_type': 'job',
  'title': 'Associate Software Developer',
  'url': 'https://internshala.com/job/detail/remote-associate-software-developer-job-at-dataknobs1754034909',
  'company_name': 'Dataknobs',
  'internship_logo': '/static/images/search/placeholder_logo.svg',
  'locations': ['Work from home'],
  'salary': '₹ 2,40,000 - 4,00,000',
  'experience': '1 year(s)',
  'posted_at': None},
 {'id': '2842078',
  'employment_type': 'job',
  'title': 'Junior Software Developer',
  'url': 'https://internshala.com/job/detail/fresher-remote-junior-software-developer-job-at-mo-sar1754026035',
  'company_name': 'Cognavi',
  'internship_logo': '/static/images/search/placeholder_logo.svg',
  'locations': ['Work from home'],
  'salary': '₹ 5,00,000 - 10,00,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2842128',
  'employment_type': 'job',
  'title': 'Senior Front End Developer',
  'url': 'https://internshala.com/job/detail/remote-senior-front-end-developer-job-at-dealzup1754025264',
  'company_name': 'Dealzup',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2F7lr4549q29r-20090.jpeg',
  'locations': ['Work from home'],
  'salary': '₹ 2,40,000',
  'experience': '1 year(s)',
  'posted_at': None},
 {'id': '2841038',
  'employment_type': 'job',
  'title': 'Java Developer',
  'url': 'https://internshala.com/job/detail/java-developer-job-in-noida-at-acme-wealth-advisory-private-limited1754024927',
  'company_name': 'Acme Wealth Advisory Private Limited',
  'internship_logo': '/static/images/search/placeholder_logo.svg',
  'locations': ['Noida'],
  'salary': '₹ 2,00,000 - 2,24,000',
  'experience': '1 year(s)',
  'posted_at': None},
 {'id': '2843766',
  'employment_type': 'job',
  'title': 'MS Dynamics 365 Software Developer',
  'url': 'https://internshala.com/job/detail/remote-ms-dynamics-365-software-developer-job-at-tymor-technologies1754024671',
  'company_name': 'Tymor Technologies',
  'internship_logo': '/static/images/search/placeholder_logo.svg',
  'locations': ['Work from home'],
  'salary': '₹ 5,00,000 - 7,00,000',
  'experience': '1 year(s)',
  'posted_at': None},
 {'id': '2843769',
  'employment_type': 'job',
  'title': 'Mid Level Web Developer',
  'url': 'https://internshala.com/job/detail/remote-mid-level-web-developer-job-at-tymor-technologies1754024618',
  'company_name': 'Tymor Technologies',
  'internship_logo': '/static/images/search/placeholder_logo.svg',
  'locations': ['Work from home'],
  'salary': '₹ 4,00,000 - 6,00,000',
  'experience': '1 year(s)',
  'posted_at': None},
 {'id': '2839543',
  'employment_type': 'job',
  'title': 'Flutter Developer',
  'url': 'https://internshala.com/job/detail/remote-flutter-developer-job-at-armii1754021220',
  'company_name': 'ARMII',
  'internship_logo': '/static/images/search/placeholder_logo.svg',
  'locations': ['Work from home'],
  'salary': '₹ 3,00,000 - 3,00,001',
  'experience': '1 year(s)',
  'posted_at': None},
 {'id': '2843441',
  'employment_type': 'job',
  'title': 'Junior Web Developer',
  'url': 'https://internshala.com/job/detail/junior-web-developer-job-in-gurgaon-at-group-futurista1753964915',
  'company_name': 'Group Futurista',
  'internship_logo': '/static/images/search/placeholder_logo.svg',
  'locations': ['Gurgaon'],
  'salary': '₹ 2,00,000 - 3,00,000',
  'experience': '1 year(s)',
  'posted_at': None}]

searched_data=[{'id': '2843024',
  'employment_type': 'job',
  'title': 'Junior Python Developer',
  'url': 'https://internshala.com/job/detail/remote-junior-python-developer-job-at-codezero2pi-solution-opc-private-limited1754289968',
  'company_name': 'Codezero2pi Solution (OPC) Private Limited',
  'internship_logo': '/static/images/search/placeholder_logo.svg',
  'locations': ['Work from home'],
  'salary': '₹ 4,00,000 - 6,00,000',
  'experience': '1 year(s)',
  'posted_at': None},
 {'id': '2845917',
  'employment_type': 'job',
  'title': 'Python Developer',
  'url': 'https://internshala.com/job/detail/fresher-remote-python-developer-job-at-mediacom-india1754283308',
  'company_name': 'MediaCom India',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2Fh02v7a8fr91-9207.png.webp',
  'locations': ['Work from home'],
  'salary': '₹ 5,00,000 - 8,00,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2842921',
  'employment_type': 'job',
  'title': 'Junior Python Developer',
  'url': 'https://internshala.com/job/detail/fresher-remote-junior-python-developer-job-at-valcon-infotech1753942463',
  'company_name': 'Valcon Infotech',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2F6utuyu7vurx-78554.png.webp',
  'locations': ['Work from home'],
  'salary': '₹ 4,00,000 - 7,00,000',
  'experience': '0 year(s)',
  'posted_at': None},
 {'id': '2837895',
  'employment_type': 'job',
  'title': 'Junior Python Developer',
  'url': 'https://internshala.com/job/detail/junior-python-developer-job-in-multiple-locations-at-genesis-technology-services-india-private-limited1753929103',
  'company_name': 'Genesis Technology Services India Private Limited',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2F5amyyjr0s8n-15027.jpg.webp',
  'locations': ['Delhi', 'Gurgaon'],
  'salary': '₹ 3,00,000 - 6,00,000',
  'experience': '1 year(s)',
  'posted_at': None},
 {'id': '2837815',
  'employment_type': 'job',
  'title': 'Senior Python Developer',
  'url': 'https://internshala.com/job/detail/remote-senior-python-developer-job-at-shardul-singh1753533144',
  'company_name': 'Shardul Singh',
  'internship_logo': '/static/images/search/placeholder_logo.svg',
  'locations': ['Work from home'],
  'salary': '₹ 2,00,000 - 3,20,000',
  'experience': '1 year(s)',
  'posted_at': '1 week ago'},
 {'id': '2827344',
  'employment_type': 'job',
  'title': 'Python Developer',
  'url': 'https://internshala.com/job/detail/fresher-remote-python-developer-job-at-aivoa1752351236',
  'company_name': 'AIVOA',
  'internship_logo': '/static/images/search/placeholder_logo.svg',
  'locations': ['Work from home'],
  'salary': '₹ 2,00,000 - 2,25,000',
  'experience': '0 year(s)',
  'posted_at': '3 weeks ago'},
 {'id': '2826188',
  'employment_type': 'job',
  'title': 'Python Developer',
  'url': 'https://internshala.com/job/detail/remote-python-developer-job-at-rsvr-technlogies-private-limited1752145195',
  'company_name': 'RSVR Technlogies Private Limited',
  'internship_logo': 'https://internshala-uploads.internshala.com/logo%2F73xh85ze7ux-26393.jpg.webp',
  'locations': ['Work from home'],
  'salary': '₹ 2,60,000 - 3,40,000',
  'experience': '1 year(s)',
  'posted_at': '3 weeks ago'},
 {'id': '2821192',
  'employment_type': 'job',
  'title': 'Python Developer',
  'url': 'https://internshala.com/job/detail/fresher-remote-python-developer-job-at-sarva-suvidhan-pvt-ltd1751682430',
  'company_name': 'Sarva Suvidhan Pvt. Ltd.',
  'internship_logo': '/static/images/search/placeholder_logo.svg',
  'locations': ['Work from home'],
  'salary': '₹ 3,00,000 - 6,00,000',
  'experience': '0 year(s)',
  'posted_at': '3 weeks ago'},
 {'id': '2816713',
  'employment_type': 'job',
  'title': 'Python Developer',
  'url': 'https://internshala.com/job/detail/python-developer-job-in-mumbai-at-fikaa1751294382',
  'company_name': 'FIKAA',
  'internship_logo': '/static/images/search/placeholder_logo.svg',
  'locations': ['Mumbai'],
  'salary': '₹ 3,00,000 - 4,50,000',
  'experience': '1 year(s)',
  'posted_at': '3 weeks ago'}]